### IF you want to deploy VIA Cloud Build using GoLang on Cloud Run WITHOUT Dockerfile
steps:
# Deploy container image to Cloud Run Services
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'inventory-service/spanner/'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  #   $_ Are Variable Substitutes https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
  - '$_SERVICE'
  - '--source'
  - '.'
  - '--region'
  #   $_ Are Variable Substitutes https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
  - '$_REGION'
  - '--platform'
  - 'managed'
  - '--port'
  #   $_ Are Variable Substitutes https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
  - '$_PORT'
  - '--update-env-vars'
  #   $_ Are Variable Substitutes https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
  - 'SOMEENV=$_SPANNER_CONNECTION_STRING'
  # If you want to add a CloudSQL Instance to your Cloud Run Service
  - '--add-cloudsql-instances=$_DB_CONNECTION'
  #--add-cloudsql-instances=$fitstack-343223:us-central1:fitstackapi
  # DB_CONNECTION should look like: <project>:<region>:<sql-instance>
#DATABASE_URL=/cloudsql/fitstack-343223:us-central1:fitstackapi