version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB=${DB_TABLE:?err}
      - POSTGRES_USER=${DB_USERNAME:?err}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?err}
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "rest-api"
    environment:
      - DB_USERNAME=${DB_USERNAME:?err}
      - DB_PASSWORD=${DB_PASSWORD:?err}
      - DB_DB=${DB_TABLE:?err}
      - DB_HOST=db
      - DB_TABLE=${DB_TABLE:?err}
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on: 
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge

#docker-compose up -d 